name: Backup SQLite Database to Google Drive

on:
  schedule:
    # Runs at 6:00 AM and 6:00 PM UTC every day
    - cron: '0 6,18 * * *'
  workflow_dispatch: # Allows manual triggering of the workflow

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      # Deploy to DigitalOcean Droplet using SSH
      - name: Backup Database to Google Drive
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Set up rclone config
            echo "[INFO]: Setting up rclone config"
            mkdir -p ~/.config/rclone
            echo "${{ secrets.RCLONE_CONFIG }}" | base64 -d > ~/.config/rclone/rclone.conf

            # Navigate to the app directory
            cd /root/app

            # Check if local sqlite.db exists
            if [ ! -f sqlite.db ]; then
              echo "[ERROR]: Local sqlite.db not found!"
              exit 1
            fi

            # Rename sqlite.db on Google Drive to include date
            echo "[INFO]: Renaming sqlite.db on Google Drive"
            DATE=$(date +%Y%m%d_%H%M%S)
            rclone moveto gdrive:/DB_Backups/Damianakos/sqlite.db gdrive:/DB_Backups/Damianakos/sqlite_${DATE}.db --ignore-errors

            # Upload local sqlite.db to Google Drive
            echo "[INFO]: Uploading local sqlite.db to Google Drive"
            rclone copy sqlite.db gdrive:/DB_Backups/Damianakos/ --ignore-errors

            echo "[INFO]: Database backup completed successfully"
